"use client";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";
import {
  arbitrum,
  base,
  mainnet,
  optimism,
  polygon,
  sepolia,
} from "wagmi/chains";
import { getDefaultConfig, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/ui/Navbar";
import { LightDarkToggle } from "@/components/ui/light-dark-toggle";
import LottieControl from "@/components/lottie/lottie";
import { AnimationProvider } from "@/context/AnimationContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const metadata: Metadata = {
  title: "Payment Notification Dapp",
  description: "Generated by create next app",
};

const config = getDefaultConfig({
  appName: "RainbowKit App",
  projectId: "YOUR_PROJECT_ID",
  // chains: [mainnet, polygon, optimism, arbitrum, base, sepolia],
  chains: [sepolia],
  ssr: true,
});
const client = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "dark")}>
        <AnimationProvider>
          <WagmiProvider config={config}>
            <QueryClientProvider client={client}>
              <RainbowKitProvider>
                <div className="relative flex items-center justify-center min-h-screen w-full">
                  <LottieControl />
                  <div className="z-10 p-2 w-full">
                    {children}
                    <LightDarkToggle className="fixed top-1/2 right-5 transform -translate-y-1/2" />
                  </div>
                </div>
              </RainbowKitProvider>
            </QueryClientProvider>
          </WagmiProvider>
        </AnimationProvider>
        <Toaster />
      </body>
    </html>
  );
}
